### PR TITLE
Bugfix/super source box parameters actual bytes placement

### PR DESCRIPTION
**Pull request by s-kol-gg**
Update All `setSuperSourceBoxParameters` functions and `_handleSSBP` function to current `SuperSource` income bytes.
Added extra docs.

### CODE REVIEW

**Comment by s-kol-gg** [comment]
@clvLabs Hi, can you check it plz?
Test it on ATEM 2 M/E Production Studio 4K - works correct.

Next code setup correct parameters:

>self.switcher.setSuperSourceBoxParametersEnabled(0, True)
self.switcher.setSuperSourceBoxParametersCropped(0, True)
self.switcher.setSuperSourceBoxParametersSize(0, 0.75)
self.switcher.setSuperSourceBoxParametersPositionX(0, 8.8)
self.switcher.setSuperSourceBoxParametersPositionY(0, -11.0)
self.switcher.setSuperSourceBoxParametersCropRight(0, 24.05)
self.switcher.setSuperSourceBoxParametersCropLeft(0, .05)
self.switcher.setSuperSourceBoxParametersCropTop(0, .05)
self.switcher.setSuperSourceBoxParametersCropBottom(0, 13.55)


Output:

> {
	0: {
		'enabled': True, 
		'source': PyATEMMax.ATEMProtocolEnums.ATEMConstant(name=mediaPlayer2, value=3020), 
		'posx': 8.8, 
		'posy': -11.0, 
		'size': 0.75, 
		'crop': True, 
		'croptop': 0.05, 
		'cropbottom': 13.55, 
		'cropleft': 0.05, 
		'cropright': 24.05
	}, 
	...
}

**Comment by clvLabs** [comment]
Hi @s-kol-gg , thanks for the pull request !!

Reading the `SSBP` message definition in the [original document from skaarhoj](https://www.skaarhoj.com/discover/blackmagic-atem-switcher-protocol) seemed as the actual code should be OK, but then I just remembered about #9 , take a look  at [this comment in the issue](https://github.com/clvLabs/PyATEMMax/issues/9#issuecomment-983171337) and you'll see what I mean.

About merging the pull request: if you don't mind me being a little _picky_, there's some questions about code aesthetics that I would like to have changed before doing the merge.

How do we proceed? Frankly, I have not much experience with pull requests and I don't want to mess up.
I think I could comment directly on lines of your commits and explain it directly there and then wait for that commit and do the merge. (Am I right?)

Mainly the issues I have are:
* [commit 8c28](https://github.com/s-kol-gg/PyATEMMax/commit/8c28f5e4ba73d3b53b018785ab84ab6665f11bf5)
  * (typo) Replace `Uncnown` with `Unknown`
* [commit 08a6](https://github.com/s-kol-gg/PyATEMMax/commit/08a6450c4784f813106dc458fcc5af2cf7486095)
  * I would not add these comments to the functions:
  ```
        ---
        Take a look to ATEMCommandHandlers._handleSSBP.
        There are you can see bytes placement and available values.
        --- @s-kol-gg
  ```
   just because that reference isn't listed in all of the other methods and I'd be forced to complete the rest. It's a nice reference to have while developing, I'll take note in my _to-do_ list to add them all, but if possible please remove them.
  * In the rest of the file some spacing changes were made besides the byte positions. I'm assuming that's the _prettifier_ in your code editor. Not telling I don't like it, it just doesn't match the rest of the code.
* [commit 0f6f](https://github.com/s-kol-gg/PyATEMMax/commit/0f6fab532789a9969d92f4e04ce0b747e315002d)
  * Same as previous commit
 

Would you mind doing those changes ?

Thanks again for your help.

**Comment by s-kol-gg** [comment]
@clvLabs I’ll done with all your comments in a couple days. Thanks for your feedback!

**Comment by s-kol-gg** [comment]
@clvLabs done ✅

**Comment by clvLabs** [comment]
Thanks a lot Sergey !!

Version [1.0b7](https://pypi.org/project/PyATEMMax/)  is now available on pypi.org, including your changes.

**Comment by s-kol-gg** [comment]
Great!  Thanks a lot!

**Pull request merged**
